version: '3'

services:

  pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix_app
    restart: always 
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/data
      - ./conf:/etc/pretix
    ports:
      - 80:80
    networks:
      - web
      - stack_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=password # CHANGE THIS!
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - stack_network
  
  redis:
    image: redis:latest
    restart: always
    networks:
      - stack_network

networks: 
  web:
    external: true
  stack_network:
    external: false
